name: wdke
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - scipy
  - pip
  - pip:
      - openai==0.28
      - sentence-transformers
      - rouge-score
      - python-dotenv
